# Generated by Django 4.1.7 on 2023-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('project', models.CharField(max_length=20)),
                ('croom', models.IntegerField()),
                ('dnum', models.IntegerField()),
                ('pwd', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('checkin', models.CharField(max_length=1)),
                ('一般项目', models.CharField(max_length=1)),
                ('内科', models.CharField(max_length=1)),
                ('外科', models.CharField(max_length=1)),
                ('眼科', models.CharField(max_length=1)),
                ('耳鼻喉', models.CharField(max_length=1)),
                ('口腔科', models.CharField(max_length=1)),
                ('静态心电图ecg', models.CharField(db_column='静态心电图ECG', max_length=1)),
                ('妇科', models.CharField(max_length=1)),
                ('尿常规12项', models.CharField(max_length=1)),
                ('血常规18项', models.CharField(max_length=1)),
                ('肝功能', models.CharField(max_length=1)),
                ('血脂', models.CharField(max_length=1)),
                ('肾功能', models.CharField(max_length=1)),
                ('血糖', models.CharField(max_length=1)),
                ('肿瘤标志物c12', models.CharField(db_column='肿瘤标志物C12', max_length=1)),
                ('幽门螺旋杆菌检测', models.CharField(max_length=1)),
                ('高清彩色多普勒b超', models.CharField(db_column='高清彩色多普勒B超', max_length=1)),
                ('电子计算机断层扫描ct', models.CharField(db_column='电子计算机断层扫描CT', max_length=1)),
            ],
            options={
                'db_table': 'exam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('marriage', models.CharField(max_length=2)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('一般项目', models.CharField(blank=True, max_length=100, null=True)),
                ('内科', models.CharField(blank=True, max_length=100, null=True)),
                ('外科', models.CharField(blank=True, max_length=100, null=True)),
                ('眼科', models.CharField(blank=True, max_length=100, null=True)),
                ('耳鼻喉', models.CharField(blank=True, max_length=100, null=True)),
                ('口腔科', models.CharField(blank=True, max_length=100, null=True)),
                ('静态心电图ecg', models.CharField(blank=True, db_column='静态心电图ECG', max_length=100, null=True)),
                ('妇科', models.CharField(blank=True, max_length=100, null=True)),
                ('尿常规12项', models.CharField(blank=True, max_length=100, null=True)),
                ('血常规18项', models.CharField(blank=True, max_length=100, null=True)),
                ('肝功能', models.CharField(blank=True, max_length=100, null=True)),
                ('血脂', models.CharField(blank=True, max_length=100, null=True)),
                ('肾功能', models.CharField(blank=True, max_length=100, null=True)),
                ('血糖', models.CharField(blank=True, max_length=100, null=True)),
                ('肿瘤标志物c12', models.CharField(blank=True, db_column='肿瘤标志物C12', max_length=100, null=True)),
                ('幽门螺旋杆菌检测', models.CharField(blank=True, max_length=100, null=True)),
                ('高清彩色多普勒b超', models.CharField(blank=True, db_column='高清彩色多普勒B超', max_length=100, null=True)),
                ('电子计算机断层扫描ct', models.CharField(blank=True, db_column='电子计算机断层扫描CT', max_length=100, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
    ]
